version: 2.1
orbs:
  jira: circleci/jira@2.0
  node: circleci/node@5.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - jira/notify:
          pipeline_id: df32f56d-6c82-4833-9db7-fd5728b75054
          pipeline_number: 4
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t emadzafar/nodejswebapp1:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u emadzafar --password-stdin
      - run:
          name: Push Docker image
          command: |
            docker push emadzafar/nodejswebapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
      - build
        context: JIRA_WEBHOOK_URL
